# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check JS Lockfile
        if: matrix.os == 'ubuntu-latest'
        uses: ChromaticHQ/javascript-lockfile-check-action@v1.1.0
        with:
          package-manager: yarn
      - name: Install dependencies
        run: yarn install

      - name: Check for eslint
        run: yarn lint

      - name: Run the tests
        run: yarn test:coverage

      - name: Build
        env:
          CI: false
        run: yarn build
