name: LintPR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    run: echo ${{ github.actor }}
    steps:
      name: semantic pr
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
